package chat.hodhod.sdk.ui

import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.w3c.dom.Element

/** Fails when any of the six supported locales lacks a key that English has (strings are generated by tools/gen_strings.py). */
class StringsParityTest {
    private val locales = listOf("fa", "ar", "de", "es", "fr")
    private val res = File("src/main/res")

    private data class Res(val strings: Map<String, String>, val plurals: Map<String, Map<String, String>>)

    private fun load(dir: String): Res {
        val strings = HashMap<String, String>()
        val plurals = HashMap<String, Map<String, String>>()
        for (name in listOf("hodhod_strings.xml", "hodhod_ui_strings.xml")) {
            val f = File(res, "$dir/$name")
            assertTrue("missing $f", f.exists())
            val doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(f)
            val nodes = doc.documentElement.childNodes
            for (i in 0 until nodes.length) {
                val n = nodes.item(i) as? Element ?: continue
                when (n.tagName) {
                    "string" -> strings[n.getAttribute("name")] = n.textContent
                    "plurals" -> {
                        val items = n.getElementsByTagName("item")
                        plurals[n.getAttribute("name")] = (0 until items.length).associate { (items.item(it) as Element).getAttribute("quantity") to items.item(it).textContent }
                    }
                }
            }
        }
        return Res(strings, plurals)
    }

    private val args = Regex("%(\\d+)\\$[sd]")
    private fun argSet(s: String) = args.findAll(s).map { it.groupValues[1] }.toSortedSet()

    @Test
    fun everyLocaleHasEveryEnglishKey() {
        val en = load("values")
        assertTrue("English has strings", en.strings.size > 250)
        for (l in locales) {
            val r = load("values-$l")
            assertEquals("$l missing strings", emptyList<String>(), (en.strings.keys - r.strings.keys).sorted())
            assertEquals("$l missing plurals", emptyList<String>(), (en.plurals.keys - r.plurals.keys).sorted())
            assertTrue("$l has blank values", r.strings.values.none { it.isBlank() })
        }
    }

    @Test
    fun placeholdersMatchEnglish() {
        val en = load("values")
        for (l in locales) {
            val r = load("values-$l")
            for ((k, v) in en.strings) assertEquals("$l/$k placeholders", argSet(v), argSet(r.strings.getValue(k)))
            // `one` forms may legitimately omit the number ("1 person ahead"), so only `other` is compared.
            for ((k, v) in en.plurals) assertEquals("$l/$k placeholders", argSet(v.getValue("other")), argSet(r.plurals.getValue(k).getValue("other")))
        }
    }

    @Test
    fun pluralQuantitiesAreCompleteForArabic() {
        val ar = load("values-ar")
        val need = setOf("zero", "one", "two", "few", "many", "other")
        ar.plurals.forEach { (k, q) -> assertEquals("ar/$k quantities", need, q.keys) }
        listOf("fa", "de", "es", "fr").forEach { l -> load("values-$l").plurals.forEach { (k, q) -> assertTrue("$l/$k has one+other", q.containsKey("one") && q.containsKey("other")) } }
    }

    @Test
    fun translationsAreNotEnglishCopies() {
        val en = load("values")
        for (l in locales) {
            val r = load("values-$l")
            val same = en.strings.filter { (k, v) -> v.length > 20 && r.strings[k] == v }.keys
            assertTrue("$l untranslated: $same", same.size <= 3)
        }
    }

    @Test
    fun rtlLocalesContainRtlScript() {
        for (l in listOf("fa", "ar")) {
            val r = load("values-$l")
            val text = r.strings.getValue("hodhod_end_screen_title")
            assertTrue("$l title is RTL script", text.any { it.code in 0x0600..0x06FF })
        }
    }
}
