package chat.hodhod.sdk.internal.flow

/** English fallback for the flow chrome strings (`CHATBOT_FLOW.*` of the widget locale); the UI module supplies localised ones via setTranslator. */
internal object DefaultFlowStrings {
    val EN: Map<String, String> = mapOf(
        "BACK" to "Back",
        "DID_THIS_HELP" to "Did this answer your question?",
        "YES_RESOLVED" to "Yes, thanks",
        "NO_NEED_AGENT" to "No, talk to an agent",
        "GLAD_IT_HELPED" to "Glad that helped!",
        "START_OVER" to "Start over",
        "CONFIRM_INPUT" to "Are you sure?",
        "EDIT_INPUT" to "Edit",
        "CONFIRM_YES" to "Yes, continue",
        "YES" to "Yes",
        "NO" to "No",
        "CONNECTING_AGENT" to "Connecting you to an agent...",
        "DEAD_END_TEXT" to "There's no answer set up for this yet. Would you like to talk to an agent?",
        "TALK_TO_AGENT" to "Talk to an agent",
        "AGENT_REQUEST_MESSAGE" to "I'd like to speak with an agent.",
        "INPUT_INVALID" to "That doesn't look right. Please check and try again.",
        "TITLE" to "Guided help",
        "CONTINUE" to "Continue",
        "SKIP" to "Skip",
        "DONE" to "Done",
        "SEND" to "Send",
        "OTHER" to "Other…",
        "OTHER_PLACEHOLDER" to "Type here…",
        "TYPING" to "The bot is typing",
        "BACK_TO_MENU" to "Back to main menu",
        "NEW_TAB" to "(opens in a new tab)",
        "BOT_BADGE" to "Bot",
        "RETRY" to "Try again",
        "HANDOFF_ERROR" to "Couldn't connect. Please try again.",
        "REASON_PROMPT" to "What went wrong?",
        "INPUT.ERROR_REQUIRED" to "This field is required.",
        "INPUT.ERROR_EMAIL" to "Enter a valid email.",
        "INPUT.ERROR_PHONE" to "Enter a valid phone number.",
        "INPUT.ERROR_NUMBER" to "Enter a valid number.",
        "INPUT.ERROR_DATE" to "Enter a valid date.",
        "INPUT.ERROR_URL" to "Enter a valid web address.",
        "INPUT.ERROR_NUMBER_MIN" to "The number must be at least {min}.",
        "INPUT.ERROR_NUMBER_MAX" to "The number must be at most {max}.",
        "INPUT.ERROR_MIN_LENGTH" to "Enter at least {min} characters.",
        "INPUT.ERROR_MAX_LENGTH" to "At most {max} characters are allowed.",
        "RATING.ARIA" to "{value} of {max}",
        "RATING.THUMBS_UP" to "Helpful",
        "RATING.THUMBS_DOWN" to "Not helpful",
        "RATING.NPS_LOW" to "Not at all likely",
        "RATING.NPS_HIGH" to "Extremely likely",
        "RATING.EMOJI_1" to "Awful",
        "RATING.EMOJI_2" to "Bad",
        "RATING.EMOJI_3" to "Okay",
        "RATING.EMOJI_4" to "Good",
        "RATING.EMOJI_5" to "Great",
        "OFFLINE.TITLE_CLOSED" to "We're closed right now",
        "OFFLINE.TITLE_NO_AGENTS" to "No agents are online right now",
        "OFFLINE.FIELD_NAME" to "Name",
        "OFFLINE.FIELD_EMAIL" to "Email",
        "OFFLINE.FIELD_PHONE" to "Phone number",
        "OFFLINE.FIELD_MESSAGE" to "Your message",
        "OFFLINE.SUBMIT" to "Send message",
        "OFFLINE.LEAVE_MESSAGE" to "Leave a message",
        "OFFLINE.SUCCESS" to "Thanks! We'll get back to you soon.",
        "OFFLINE.ERROR_CHANNEL" to "Enter an email or phone number so we can reply.",
        "IDLE.DEFAULT_MESSAGE" to "Still there? We can connect you to an agent if you need help.",
        "WEBHOOK.LOADING" to "One moment…",
        "WEBHOOK.ERROR" to "We couldn't fetch that right now.",
        "CREATING_TICKET" to "Submitting your ticket…",
        "TICKET_REQUEST_MESSAGE" to "Ticket request from the chatbot",
    )
}
