#!/usr/bin/env python3
"""Hodhod widget i18n JSON -> Android string resources.

Reads chatwoot/app/javascript/widget/i18n/locale/{en,fa,ar,de,es,fr}.json and writes
hodhod-ui/src/main/res/values[-xx]/hodhod_strings.xml so the SDK stays in sync with the web widget.

Rules
  * key path  A.B.C            -> resource  hodhod_a_b_c
  * "x | y"   (vue-i18n plural) -> <plurals> (one = x, other = y; extra CLDR quantities of ar copy `other`)
  * {name}                      -> positional %N$s ; {n}/{count}/{min}... in plurals -> %N$d.
                                   Positional index = alphabetical order of the placeholder names in the
                                   ENGLISH string, so every locale uses the same argument order
                                   (e.g. {a} {b} -> getString(id, a, b)). Documented in README.
  * English is the default (res/values); other locales only contain keys they translate
    (missing ones fall back to English automatically, `tools:ignore=MissingTranslation`).

Usage:  python3 tools/gen_strings.py [--src <locale dir>] [--out <res dir>]
The generated hodhod_strings.xml files are COMMITTED; this script is a maintainer tool and is NOT part of the
Gradle build (a clean checkout builds without the Rails tree).
"""
import argparse, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_SRC = os.path.normpath(os.path.join(ROOT, '..', 'chatwoot', 'app', 'javascript', 'widget', 'i18n', 'locale'))
DEFAULT_OUT = os.path.join(ROOT, 'hodhod-ui', 'src', 'main', 'res')
LOCALES = ['en', 'fa', 'ar', 'de', 'es', 'fr']
PH = re.compile(r'\{([A-Za-z_][A-Za-z0-9_]*)\}')
NUMERIC = {'n', 'count', 'min', 'hours', 'minutes'}
AR_QTY = ['zero', 'one', 'two', 'few', 'many', 'other']


def flatten(obj, prefix=''):
    for k, v in obj.items():
        key = f'{prefix}_{k}' if prefix else k
        if isinstance(v, dict):
            yield from flatten(v, key)
        elif isinstance(v, str):
            yield key, v


def res_name(key):
    return 'hodhod_' + re.sub(r'[^a-z0-9_]', '_', key.lower())


def esc(s):
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')
    s = s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    s = s.replace('%', '%%').replace('@', '\\@').replace('\n', '\\n')
    if s.startswith('?'):
        s = '\\' + s
    return s


def convert(text, order, plural):
    """escape + replace placeholders with positional format args."""
    out = esc(text)
    def sub(m):
        name = m.group(1)
        if name not in order:
            order.append(name)
        idx = order.index(name) + 1
        conv = 'd' if (plural and name in NUMERIC) else 's'
        return f'%{idx}${conv}'
    # placeholders contain only [A-Za-z0-9_{}] so escaping above leaves them intact
    return PH.sub(sub, out)


def en_order(text):
    return sorted(set(PH.findall(text)))


def is_plural(text):
    return ' | ' in text


def build(locale, data, en_flat):
    flat = dict(flatten(data))
    for k, tr in OVERRIDE.items():
        if locale in tr:
            flat[k] = tr[locale]
    for k, tr in SUPPLEMENT.items():
        if k not in flat and locale in tr:
            flat[k] = tr[locale]
    missing = [k for k in en_flat if k not in flat]
    if missing:
        print(f'[gen_strings] WARNING {locale}: missing {missing} -> English fallback', file=sys.stderr)
        for k in missing:
            flat[k] = en_flat[k]
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- GENERATED by tools/gen_strings.py from the web widget i18n locale JSON. DO NOT EDIT. -->',
             '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation,ExtraTranslation,PluralsCandidate,TypographyEllipsis,Typos,ImpliedQuantity,UnusedResources">']
    for key in en_flat:
        if key not in flat:
            continue
        val = flat[key]
        order = en_order(en_flat[key])
        # placeholders only present in the translation get appended deterministically
        for p in sorted(set(PH.findall(val))):
            if p not in order:
                order.append(p)
        name = res_name(key)
        if is_plural(en_flat[key]) or is_plural(val):
            forms = [f.strip() for f in val.split(' | ')]
            one = forms[0]
            other = forms[-1] if len(forms) > 1 else forms[0]
            qty = {'one': one, 'other': other}
            if locale == 'ar':
                for q in AR_QTY:
                    qty.setdefault(q, other)
            elif locale in ('es', 'fr'):
                qty.setdefault('many', other)
            lines.append(f'    <plurals name="{name}">')
            for q in ['zero', 'one', 'two', 'few', 'many', 'other']:
                if q in qty:
                    lines.append(f'        <item quantity="{q}">{convert(qty[q], list(order), True)}</item>')
            lines.append('    </plurals>')
        else:
            lines.append(f'    <string name="{name}">{convert(val, list(order), False)}</string>')
    lines.append('</resources>')
    return '\n'.join(lines) + '\n'


# Strings the native UI needs that do not exist in the web widget JSON (kept here so all 6 locales stay together).
EXTRA = {
    'hodhod_ui_offline': {
        'en': 'You are offline. Reconnecting…', 'fa': 'اتصال برقرار نیست. در حال اتصال مجدد…', 'ar': 'لا يوجد اتصال. جارٍ إعادة الاتصال…',
        'de': 'Keine Verbindung. Verbindung wird wiederhergestellt…', 'es': 'Sin conexión. Reconectando…', 'fr': 'Pas de connexion. Reconnexion…'},
    'hodhod_ui_retry': {
        'en': 'Retry', 'fa': 'تلاش دوباره', 'ar': 'إعادة المحاولة', 'de': 'Erneut versuchen', 'es': 'Reintentar', 'fr': 'Réessayer'},
    'hodhod_ui_generic_error': {
        'en': 'Something went wrong. Please try again.', 'fa': 'مشکلی پیش آمد. دوباره تلاش کنید.', 'ar': 'حدث خطأ ما. حاول مرة أخرى.',
        'de': 'Etwas ist schiefgelaufen. Bitte erneut versuchen.', 'es': 'Algo salió mal. Inténtalo de nuevo.', 'fr': "Une erreur s'est produite. Veuillez réessayer."},
    'hodhod_ui_discard': {
        'en': 'Delete', 'fa': 'حذف', 'ar': 'حذف', 'de': 'Löschen', 'es': 'Eliminar', 'fr': 'Supprimer'},
    'hodhod_ui_attach_photo': {
        'en': 'Photo or video', 'fa': 'عکس یا ویدیو', 'ar': 'صورة أو فيديو', 'de': 'Foto oder Video', 'es': 'Foto o vídeo', 'fr': 'Photo ou vidéo'},
    'hodhod_ui_attach_camera': {
        'en': 'Take a photo', 'fa': 'گرفتن عکس', 'ar': 'التقاط صورة', 'de': 'Foto aufnehmen', 'es': 'Hacer una foto', 'fr': 'Prendre une photo'},
    'hodhod_ui_attach_file': {
        'en': 'File', 'fa': 'فایل', 'ar': 'ملف', 'de': 'Datei', 'es': 'Archivo', 'fr': 'Fichier'},
    'hodhod_ui_scroll_bottom': {
        'en': 'Jump to latest messages', 'fa': 'رفتن به آخرین پیام‌ها', 'ar': 'الانتقال إلى أحدث الرسائل', 'de': 'Zu den neuesten Nachrichten',
        'es': 'Ir a los últimos mensajes', 'fr': 'Aller aux derniers messages'},
    'hodhod_ui_tickets_filter_open': {
        'en': 'Open', 'fa': 'باز', 'ar': 'مفتوحة', 'de': 'Offen', 'es': 'Abiertos', 'fr': 'Ouverts'},
    'hodhod_ui_tickets_filter_closed': {
        'en': 'Closed', 'fa': 'بسته', 'ar': 'مغلقة', 'de': 'Geschlossen', 'es': 'Cerrados', 'fr': 'Fermés'},
    'hodhod_ui_tickets_filter_all': {
        'en': 'All', 'fa': 'همه', 'ar': 'الكل', 'de': 'Alle', 'es': 'Todos', 'fr': 'Tous'},
    'hodhod_ui_tickets_filter_label': {
        'en': 'Filter tickets', 'fa': 'فیلتر تیکت\u200cها', 'ar': 'تصفية التذاكر', 'de': 'Tickets filtern', 'es': 'Filtrar tickets', 'fr': 'Filtrer les tickets'},
    'hodhod_ui_tickets_open_count': {
        'en': '{n} open', 'fa': '{n} باز', 'ar': '{n} مفتوحة', 'de': '{n} offen', 'es': '{n} abiertos', 'fr': '{n} ouverts'},
    'hodhod_ui_tickets_total_count': {
        'en': '{n} in total', 'fa': '{n} مورد در مجموع', 'ar': 'المجموع {n}', 'de': '{n} insgesamt', 'es': '{n} en total', 'fr': '{n} au total'},
    'hodhod_ui_tickets_new': {
        'en': 'New ticket', 'fa': 'تیکت جدید', 'ar': 'تذكرة جديدة', 'de': 'Neues Ticket', 'es': 'Nuevo ticket', 'fr': 'Nouveau ticket'},
    'hodhod_ui_tickets_from_chat': {
        'en': 'From chat', 'fa': 'از گفت\u200cوگو', 'ar': 'من المحادثة', 'de': 'Aus dem Chat', 'es': 'Del chat', 'fr': 'Depuis le chat'},
    'hodhod_ui_tickets_empty_open': {
        'en': 'You have no open tickets.', 'fa': 'تیکت بازی ندارید.', 'ar': 'ليس لديك تذاكر مفتوحة.', 'de': 'Du hast keine offenen Tickets.', 'es': 'No tienes tickets abiertos.', 'fr': "Vous n'avez aucun ticket ouvert."},
    'hodhod_ui_tickets_empty_closed': {
        'en': 'No closed tickets yet.', 'fa': 'هنوز تیکت بسته\u200cای ندارید.', 'ar': 'لا توجد تذاكر مغلقة بعد.', 'de': 'Noch keine geschlossenen Tickets.', 'es': 'Aún no hay tickets cerrados.', 'fr': "Aucun ticket fermé pour l'instant."},
    'hodhod_ui_tickets_load_more': {
        'en': 'Load more', 'fa': 'بارگذاری بیشتر', 'ar': 'تحميل المزيد', 'de': 'Mehr laden', 'es': 'Cargar más', 'fr': 'Charger plus'},
    'hodhod_ui_tickets_updated': {
        'en': 'Updated {time}', 'fa': 'به\u200cروزرسانی {time}', 'ar': 'آخر تحديث {time}', 'de': 'Aktualisiert {time}', 'es': 'Actualizado {time}', 'fr': 'Mis à jour {time}'},
    'hodhod_ui_tickets_open_chat_hint': {
        'en': 'Opens your current chat', 'fa': 'گفت\u200cوگوی فعلی شما باز می\u200cشود', 'ar': 'يفتح محادثتك الحالية', 'de': 'Öffnet deinen aktuellen Chat', 'es': 'Abre tu chat actual', 'fr': 'Ouvre votre chat en cours'},
    'hodhod_ui_announcement_dismiss': {
        'en': 'Dismiss', 'fa': 'بستن', 'ar': 'إغلاق', 'de': 'Schließen', 'es': 'Cerrar', 'fr': 'Fermer'},
    'hodhod_ui_announcement_notice': {
        'en': 'Notice', 'fa': 'اطلاعیه', 'ar': 'إشعار', 'de': 'Hinweis', 'es': 'Aviso', 'fr': 'Information'},
    'hodhod_ui_announcement_alert': {
        'en': 'Warning', 'fa': 'هشدار', 'ar': 'تحذير', 'de': 'Warnung', 'es': 'Advertencia', 'fr': 'Avertissement'},
    'hodhod_ui_tickets_now': {
        'en': 'just now', 'fa': 'همین الان', 'ar': 'الآن', 'de': 'gerade eben', 'es': 'ahora mismo', 'fr': "à l'instant"},
}


# Keys that exist in the web `en.json` but are missing from some source locale JSON (the Rails tree is read-only for us).
SUPPLEMENT = {
    'ISSUE_NOTICE_DISMISS': {'ar': 'إخفاء الإشعار', 'de': 'Hinweis schließen', 'es': 'Descartar aviso', 'fr': "Ignorer l'avis"},
}

# Source strings that are still English copies in the web ar/de JSON: use real translations (keys are flattened with '_').
OVERRIDE = {
    'REPLY_TIME_BACK_IN_HOURS': {'ar': 'سنعود متصلين خلال {n} ساعة | سنعود متصلين خلال {n} ساعات', 'de': 'Wir sind in {n} Stunde wieder online | Wir sind in {n} Stunden wieder online'},
    'REPLY_TIME_BACK_IN_MINUTES': {'ar': 'سنعود متصلين خلال {time} دقيقة', 'de': 'Wir sind in {time} Minuten wieder online'},
    'REPLY_TIME_BACK_AT_TIME': {'ar': 'سنعود متصلين الساعة {time}', 'de': 'Wir sind um {time} wieder online'},
    'REPLY_TIME_BACK_ON_DAY': {'ar': 'سنعود متصلين يوم {day}', 'de': 'Wir sind am {day} wieder online'},
    'REPLY_TIME_BACK_IN_SOME_TIME': {'ar': 'سنعود متصلين بعد قليل', 'de': 'Wir sind in Kürze wieder online'},
    'REPLY_TIME_BACK_TOMORROW': {'de': 'Wir sind morgen wieder online'},
    'TEAM_AVAILABILITY_BACK_AS_SOON_AS_POSSIBLE': {'de': 'Wir sind so bald wie möglich wieder da'},
    'EMOJI_ICON_PICKER_SEARCH_EMOJI': {'ar': 'ابحث عن إيموجي…'},
    'EMOJI_ICON_PICKER_FREQUENTLY_USED': {'ar': 'الأكثر استخدامًا'},
    'PRE_CHAT_FORM_FIELDS_PHONE_NUMBER_DROPDOWN_SEARCH': {'de': 'Land suchen'},
}


def build_extra(locale):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- GENERATED by tools/gen_strings.py (EXTRA table). DO NOT EDIT. -->',
             '<resources>']
    for name, tr in EXTRA.items():
        lines.append(f'    <string name="{name}">{convert(tr[locale], en_order(tr["en"]), False)}</string>')
    lines.append('</resources>')
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default=DEFAULT_SRC)
    ap.add_argument('--out', default=DEFAULT_OUT)
    ap.add_argument('--check', action='store_true', help='fail if output would change')
    a = ap.parse_args()
    if not os.path.isdir(a.src):
        print(f'[gen_strings] source {a.src} not found; keeping committed strings', file=sys.stderr)
        return 0
    en_flat = dict(flatten(json.load(open(os.path.join(a.src, 'en.json'), encoding='utf-8'))))
    changed = 0
    for loc in LOCALES:
        data = json.load(open(os.path.join(a.src, f'{loc}.json'), encoding='utf-8'))
        xml = build(loc, data, en_flat)
        d = os.path.join(a.out, 'values' if loc == 'en' else f'values-{loc}')
        os.makedirs(d, exist_ok=True)
        p = os.path.join(d, 'hodhod_strings.xml')
        old = open(p, encoding='utf-8').read() if os.path.exists(p) else None
        if old != xml:
            changed += 1
            if not a.check:
                open(p, 'w', encoding='utf-8').write(xml)
        px = os.path.join(d, 'hodhod_ui_strings.xml')
        xx = build_extra(loc)
        if (open(px, encoding='utf-8').read() if os.path.exists(px) else None) != xx:
            changed += 1
            if not a.check:
                open(px, 'w', encoding='utf-8').write(xx)
        print(f'[gen_strings] {loc}: {xml.count("<string ")} strings, {xml.count("<plurals ")} plurals')
    if a.check and changed:
        print('[gen_strings] out of date', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
